RedisWeb/Models/ErrorViewModel.cs
using System;

namespace RedisWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisWeb/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using RedisWeb.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class BaseController : Controller
    {
        private readonly RedisService _redisService;
        protected readonly IDatabase db;
        public BaseController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDb(0);
        }
    }
}

RedisWeb/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisWeb.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class HashTypeController : BaseController
    {
        public string hashKey { get; set; } = "sozluk";
        public HashTypeController(RedisService redisService) : base(redisService)
        {
        }

        public IActionResult Index()
        {
            Dictionary<string, string> list = new Dictionary<string, string>();
            if(db.KeyExists(hashKey))
            {
                var aa = db.HashGetAll(hashKey).ToList();
                foreach (var item in aa)
                {
                    list.Add(item.Name, item.Value);
                }
            }
            return View(list);
        }
        [HttpPost]
        public IActionResult Add(string name, string value)
        {
            db.HashSet(hashKey, name, value);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(string name)
        {
            db.HashDelete(hashKey, name);
            return RedirectToAction("Index");
        }
    }
}

RedisWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RedisWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisWeb/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisWeb.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase db;
        private string key = "names";
        public ListTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDb(0);
        }
        public IActionResult Index()
        {
            List<string> nameList = new();
            if (db.KeyExists(key))
            {
                db.ListRange(key).ToList().ForEach(x =>
                {
                    nameList.Add(x.ToString());
                });

            }
            return View(nameList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            if(name is not null)
            {
                db.ListRightPushAsync(key, name);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(string name)
        {
            db.ListRemoveAsync(key, name).Wait();
            return RedirectToAction("Index");
        }
    }
}

RedisWeb/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisWeb.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class SetTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase db;
        private string key = "setnames";
        public SetTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDb(0);
        }
        public IActionResult Index()
        {
            HashSet<string> nameList = new HashSet<string>();
            if (db.KeyExists(key))
            {
                var dbList = db.SetMembers(key).ToList();
                foreach (var item in dbList)
                {
                    nameList.Add(item.ToString());
                }
            }
            return View(nameList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            if (name is not null)
            {
                db.KeyExpire(key, DateTime.Now.AddMinutes(5));
                db.SetAdd(key, name);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(string name)
        {
            db.SetRemoveAsync(key, name).Wait();
            return RedirectToAction("Index");
        }
    }
}

RedisWeb/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisWeb.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisWeb.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase db;
        public StringTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db= _redisService.GetDb(0);
        }
        public IActionResult Index()
        { 
            db.StringSet("name", "Bugrahan SAYGICI");
            db.StringSet("uni", "Pamukkale Universitesi");
            db.StringSet("telno", "5419766556");
            db.StringIncrement("goruntulenmesayisi",1);
            return View();
        }
        public IActionResult Get()
        {
            var name = db.StringGet("name");
            var nameLength = db.StringLength("name");
            var getRange = db.StringGetRange("name",0,10);
            var uni = db.StringGet("uni");
            var no = db.StringGet("telno");
            var goruntulenmesayisi = db.StringGet("goruntulenmesayisi");

            if(name.HasValue)
            {
                ViewBag.name = name;
            }
            ViewBag.uni = uni.IsNullOrEmpty?"Bilinmiyor":uni.ToString(); 
            ViewBag.getRange = getRange.IsNullOrEmpty?"Bilinmiyor": getRange.ToString(); 
            ViewBag.no = no.IsNullOrEmpty ? "Bilinmiyor" : no.ToString();
            ViewBag.goruntulenmesayisi = goruntulenmesayisi.IsNullOrEmpty ? "Bilinmiyor" : goruntulenmesayisi.ToString();
            ViewBag.nameLength = nameLength==0 ? "Bilinmiyor" : nameLength.ToString();
            return View();
        }
    }
}

RedisWeb/Views/HashType/Index.cshtml
@model Dictionary<string,string>

@{
    ViewData["Title"] = "Index";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <input type="text" name="value" />
    <button type="submit">Add</button>
</form>
@foreach (var item in Model)
{
    <h2>@item.Key ==> @item.Value <a asp-action="Delete" asp-route-name="@item.Key">Delete</a></h2>
}

RedisWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisWeb/Views/ListType/Index.cshtml
@model List<string>

@{
    ViewData["Title"] = "Index";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Add</button>
</form>
@foreach (var item in Model)
{
    <h2>@item <a asp-controller="ListType" asp-action="Delete" asp-route-name="@item">Delete</a></h2>
}

RedisWeb/Views/SetType/Index.cshtml
@model HashSet<string>
@{
    ViewData["Title"] = "Index";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Add</button>
</form>
@foreach (var item in Model)
{
    <h2>@item <a asp-controller="SetType" asp-action="Delete" asp-route-name="@item">Delete</a></h2>
}

RedisWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StringType" asp-action="Index">StringType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListType" asp-action="Index">ListType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SetType" asp-action="Index">SetType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HashType" asp-action="Index">HashType</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RedisWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RedisWeb/Views/StringType/Get.cshtml
@{
    ViewData["Title"] = "Get";
}

<h2>@ViewBag.name</h2>
<h2>@ViewBag.uni</h2>
<h2>@ViewBag.no</h2>
<h2>@ViewBag.goruntulenmesayisi</h2>
<h2>@ViewBag.getRange</h2>
<h2>@ViewBag.nameLength</h2>

RedisWeb/Views/StringType/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<a class="nav-link text-dark" asp-area="" asp-controller="StringType" asp-action="Get">GET</a>